### PR TITLE
fix(remove updateHasManyThrough casting)

### PR DESCRIPTION
**Pull request by BenjaminHorn**

### CODE REVIEW

**Comment by Tronix117** [comment]
The tests are failing, but I fixed the issue why the tests are failing in #246 just need @digitalsadhu to accept #246 first, and your Travic will goes through.

**Comment by Tronix117** [comment]
Just have a suggestion [here](https://github.com/digitalsadhu/loopback-component-jsonapi/pull/258/commits/d311fe454dc63cfdd15d9d1ef31d221de746a6f0#diff-9af465a047a4fa7d0c3c74dae92c8179R160) the `map` is useless, you could use `const newIds = rightFKValues` or remove the `newIds` variable.

**Comment by BenjaminHorn** [comment]
Good catch @Tronix117! I removed the unnecessary mapping.

**Comment by digitalsadhu** [comment]
I’ve merged #246. If you do a rebase perhaps the tests will start passing and we can get this one in too.

**Comment by Tronix117** [comment]
You should have forced push instead of making a pull on your branch `string-ids` when you made the `git pull` it merged your previous tree with your new one.

Please, on your branch `string-ids` cancel the merge by doing `git reset --hard fa27b9a` and push the branch using `--force`, it will replace the current fucked-up branch.

Thank you

**Comment by Tronix117** [comment]
Ok pour moi ! ;)

**Comment by digitalsadhu** [comment]
Nice! Thanks guys. I'll ignore the (very minor) coverage decrease and merge.

**Pull request merged**
