### PR TITLE
Added debug and enable option

### PR DESCRIPTION
**Pull request by listepo**

### CODE REVIEW

**Comment by digitalsadhu** [comment]
@listepo Nice! 
What do you think about also including `debug` as an option that can be passed in (instead of just environment variable)

eg. 
```js
if (options.debug === true) {
  //set process.env.DEBUG here
}
```

Thoughts?

**Comment by listepo** [comment]
@digitalsadhu, good idea, I thought about it.

**Comment by listepo** [comment]
@digitalsadhu https://www.youtube.com/watch?v=Foi54om6oGQ and https://www.youtube.com/watch?v=gJ0IGPa8SCc good video :+1:  advise to look

**Comment by digitalsadhu** [comment]
Nice! Thanks, i'll watch those tonight!

**Comment by digitalsadhu** [comment]
On second thought, maybe since strongloop uses the debug module in the same way its ok to just have it be an environment variable. 

I'll merge for now. We can open another PR if we want to add debug as an option.

**Pull request merged**
