### PR TITLE
Added failing test to show not being able to create a through model directly

### PR DESCRIPTION
**Pull request by taras**
I'm trying to create a through model via POST to `/interests` but I'm getting an error without stacktrace. 

```
[{ status: 500,
    source: '',
    title: 'TypeError',
    code: '',
    detail: 'Cannot read property \'id\' of null' 
} ]
```

### CODE REVIEW

**Comment by taras** [comment]
I did a bit more digging and it seems that it eventually ends up in relationships on line https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/lib/relationships.js#L47 but stops execution because id doesn't exist. I believe the error is thrown because of this https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/lib/create.js#L27

**Comment by digitalsadhu** [comment]
@taras thanks for digging further. I'll try to take a look soon

**Comment by taras** [comment]
I can do it if you can suggest a strategy to move forward. relationships needs id which we don't have on creation. 

One way can be to create a record with an id and then let relationships update it further, but Ideally, we would create a record with belongsTo relationship right away.

**Comment by digitalsadhu** [comment]
@taras any chance you can merge master onto this branch and see if tests pass now? Added a fix for another issue and just wondering if it might fix this one.

**Comment by taras** [comment]
Done, I don't think it'll fix it. It didn't in my branch. I'm looking into this further. It looks like a model is being created but somewhere around parseResource the id is lost.

**Comment by taras** [comment]
Got it! https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/lib/serializer.js#L131 returns null because no attributes are present

```
  // If there is no attributes found return
  if (_.isEmpty(attributes)) {
    return null;
  }
```

**Comment by digitalsadhu** [comment]
Ohhhh that makes sense.
Over ambitious check there I guess.
Got a fix in mind?

**Comment by taras** [comment]
I think a more appropriate check is 

```javascript
if (_.isEmpty(resource.id)){
  return null;
}
```

There is a problem with include test https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/test/include.test.js#L18. It's allowing data to be serialized for objects without an id. Looking into why this is happening.

**Comment by digitalsadhu** [comment]
Nice.

**Pull request merged**
