### PR TITLE
Feature: implement `include` functionality to sideload relationships

### LINKED ISSUE #38: Including relationship data when fetching data (aka side loading)
@listepo @tsteuwer 
Below is a write up of my understanding of what we need to do to support returning relationship information in GET requests to /:collection and /:collection/:id

Does it look right?

---------

Loopback allows you to control when relationship data is returned with a url filter:

Eg. 
- GET /:collection?filter={"include": "author"}
- GET /:collection/:id?filter={"include": "author"}

Looking at the JSON API spec: 

>If an endpoint supports the include parameter and a client supplies it, the server MUST NOT include unrequested resource objects in the included section of the compound document.

>The value of the include parameter MUST be a comma-separated (U+002C COMMA, ",") list of relationship paths. A relationship path is a dot-separated (U+002E FULL-STOP, ".") list of relationship names.

>If a server is unable to identify a relationship path or does not support inclusion of resources from a path, it MUST respond with 400 Bad Request.

the ideal would be something like: 

Eg. no include filter in url
GET http://localhost:3000/api/posts/9
```js
{
  "data": {
    "type": "posts",
    "id": "9",
    "attributes": {
      "title": "test post",
      "content": "ttseas"
    },
    "relationships": {
      "author": {
        "links": {
          "related": "http://localhost:3000/posts/9/author"
        }
      }
    }
    "links": {
      "self": "http://localhost:3000/api/posts/9"
    }
  },
  "links": {
    "self": "http://localhost:3000/api/posts/9"
  }
}
```

Eg. include filter in url
GET http://localhost:3000/api/posts/9?filter={"include":"author"}
```js
{
  "data": {
    "type": "posts",
    "id": "9",
    "attributes": {
      "title": "test post",
      "content": "ttseas"
    },
    "relationships": {
      "author": {
        "links": {
          "related": "http://localhost:3000/posts/9/author"
        },
        "data": { "type": "people", "id": "1" }
      }
    }
    "links": {
      "self": "http://localhost:3000/api/posts/9"
    }
  },
  "links": {
    "self": "http://localhost:3000/api/posts/9?filter=%7B%22include%22%3A%20%22author%22%7D"
  },
  "included": [{
    "type": "people",
    "id": "1",
    "attributes": {
      "name": "Bob Jones"
    },
    "links": {
      "self": "http://localhost:3000/people/1"
    }
  }]
}
```

- [x] add thorough test coverage for items below:
- [x] include relationships link in GET requests for collections and resources eg.  "author": { "links": { "related": "http://localhost:3000/posts/9/author" }}
- [x] rewrite url &include=author -> filter={"include":"author"} to support spec requirement
- [x] return 400 error if non existent relationship is included in url eg. &include=idontexist
- [x] remove FK links out of any `attributes` objects. Probably only applies to belongsTo relationship

### PR DESCRIPTION
**Pull request by tsteuwer**
This should fix #38

### CODE REVIEW

**Comment by tsteuwer** [comment]
@digitalsadhu assigning this to you so you can code review. I'm not sure if there's a simpler way to handle this? If there is, we may want to scrap this branch (or keep it in the meanwhile and start a new one).

**Comment by digitalsadhu** [comment]
Nice work @tsteuwer 
I think we might consider a slightly different approach in a couple places.
Lookbacks built in `include` feature can probably be leveraged.
Currently if I do:
```
http://localhost:3000/api/projects?filter={"include":"company"}
```
or
```
http://localhost:3000/api/projects?filter[include]=company
```

Then I get the following response:
```
{
  "data": [
    {
      "type": "projects",
      "relationships": {
        "company": {
          "links": {
            "related": "http://localhost:3000/api/projects/1/company"
          }
        }
      },
      "id": "1",
      "attributes": {
        "name": "A project",
        "reference": "My project ref",
        "location": "Oslo",
        "summary": "A big project",
        "created-by": 1,
        "company": {
          "name": "ABC Digging",
          "id": 1
        }
      },
      "links": {
        "self": "http://localhost:3000/api/projects/1"
      }
    },
...
```
The `company` relationship has been nested..in the wrong place (in attributes)

My thinking was that we could do:
1. Move the related data out of attributes and into included (and do any other clean up)
2. Do what you are doing now, listening for include=company on the query and then map that to how loopback already does include.

Thoughts?

**Comment by tsteuwer** [comment]
Perfect. This is why I wanted you to look at it. :) I'll revise everything tonight! Thanks!

**Comment by digitalsadhu** [comment]
Nice!

**Comment by digitalsadhu** [comment]
@tsteuwer I've uncommented all the tests relevant to this feature. Now all you have to do is make them pass! ;)

**Comment by tsteuwer** [comment]
Awesome! I'm on it :)

**Comment by digitalsadhu** [comment]
How you getting on @tsteuwer need any help?

**Comment by tsteuwer** [comment]
Sorry, in Georgia for the weekend to see family. Will get to it on Sunday or Monday

**Comment by digitalsadhu** [comment]
All good! I don't mean to be pushy, just checking in. :)

**Pull request closed without merging**
