### PR TITLE
Fix 406 Not Acceptable

### LINKED ISSUE #31: 406 Not Acceptable
It looks like we are not doing something correctly. The JSON API spec is shows:

> Servers **MUST** respond with a `406 Not Acceptable` status code if a request's `Accept` header contains the JSON API media type and all instances of that media type are modified with media type parameters.

However, when sending an actual `POST` message with `Accept: application/vnd.api+json`, the component is responding with a `406 Not Acceptable`.

### PR DESCRIPTION
**Pull request by digitalsadhu**
Not ready to merge,
Opening early for visibility,

So far, just added a failing test.
Aiming to fix #31 here

### CODE REVIEW

**Comment by digitalsadhu** [comment]
It looks there's 2 things going on. 

1. Loading order for the component is important. When it is loaded after adding the loopback.rest() middleware you see a 406 error as mentioned in this issue. 

2. Something about the way we are setting up our app in tests means that the bodyparser module is not parsing application/vnd.api+json 

Will keep looking into it today.

**Comment by digitalsadhu** [comment]
It took me all day, but I believe I finally cracked this one.
406 Not Acceptable no more
@listepo @tsteuwer

**Comment by digitalsadhu** [comment]
For reference, see comment here:
https://github.com/strongloop/loopback/issues/445#issuecomment-150923129

**Comment by digitalsadhu** [comment]
Ok, it didn't exactly take all day. More like 3 hours or something.

**Comment by tsteuwer** [comment]
Is this OK to merge?

**Comment by digitalsadhu** [comment]
@tsteuwer it is now.

**Pull request merged**
